### PR TITLE
Fixed bug which caused an assertion failure when receivers are slow

### PR DESCRIPTION
**Pull request by nickovs**
The underlying problem for issue #46 causes the library to suffer an assertion failure when the client reads the reply from the receiver more quickly than the receiver sends the data. This is most apparent when the reply is long (as with the XML reply to the `NRIQSTN` command) but can in theory happen for any command since the library did not check that the length of the data read back matches the response body length given in the header.

This patch fixes the issue and allows commands such as `NRIQSTN` to function correctly.

### CODE REVIEW

**Comment by nickovs** [comment]
Hi @miracle2k. Is there any chance that you can take a look at this PR and ideally merge it? This bug is a blocker for Home Assistant being able to [properly set the volume](https://github.com/home-assistant/home-assistant/issues/10712) on modern Onkyo amplifiers.

**Comment by miracle2k** [comment]
Sorry for missing this. Looks good!

**Comment by nickovs** [comment]
Thanks for merging this. Do you have a time-line for when you might do the next tagged release and push it out to PyPI?

**Comment by nickovs** [comment]
Is there any chance that you can update the version on PyPI to include this fix? It would be very helpful to have this available through `pip`.

**Comment by miracle2k** [comment]
A new version is online.

**Comment by nickovs** [comment]
Thanks!

**Pull request closed without merging**
