### PR TITLE
Fix issue where attempting to select the 'TV' source actually selects…

### LINKED ISSUE #60: Sending command to select 'TV' source results in selecting 'CD' source
I have an Onkyo TX-NR646.  Using this library within [Home Assistant](https://home-assistant.io).  When I select the TV source using the library, my receiver instead selects the CD source.  Looking at [commands.py](https://github.com/miracle2k/onkyo-eiscp/blob/3768523e7f296b1a88441b83256fbb9457e4a2ce/eiscp/commands.py#L3100), it's sending a value of 23 for the TV source when it should be sending 12 (see [here](https://github.com/miracle2k/onkyo-eiscp/blob/62c4b8fdc3c4ab537805e087ccadb56bf6433c1b/eiscp-commands.yaml#L3529)).  I believe this is happening due to the multiple names for value 23 [here](https://github.com/miracle2k/onkyo-eiscp/blob/62c4b8fdc3c4ab537805e087ccadb56bf6433c1b/eiscp-commands.yaml#L3545).  I'm not sure what the fix is, though.  Perhaps `name: [cd, tv, cd]` should be changed to `name: [cd, tv/cd]`?

### PR DESCRIPTION
**Pull request by joe248**
… the 'CD' source.  This should fix #60 / #61

### CODE REVIEW

**Comment by miracle2k** [comment]
Thanks!

**Comment by joe248** [comment]
Thanks for merging!  Would you mind doing a new release so we can point to it in Home Assistant?

**Comment by miracle2k** [comment]
Done.

**Comment by joe248** [comment]
Thanks!

**Comment by joe248** [comment]
Actually, I just realized that[ commands.py is now using a value of 20](https://github.com/miracle2k/onkyo-eiscp/blob/641822ea0909c00173ddb287c0c3a5b5c8bbd851/eiscp/commands.py#L3112) instead of the correct value of 12.

It looks like there are other sources in eiscp-commands.yaml like Game/TV and TV/Tape that need to be corrected as well in order to fix this.  I can do that, but should I make the commits to this branch or create a new issue and branch?

**Comment by miracle2k** [comment]
Doesn't matter. Any pull request on Github is fine. If you editing the files on the web, just press edit.

**Pull request merged**
