### PR TITLE
Added HDMI-CEC TV control support

### PR DESCRIPTION
**Pull request by kadamiec**
Hello,
I have made clean implementation of CTV command (to control TV via HDMI-CEC).
I did followed RELEASING howto, i hope this helps to get this merged.

Thanks in advance!
Kind regards,
K

### CODE REVIEW

**Comment by kadamiec** [comment]
Since Python 3.3 is no longer supported by travis-ci (after migration to Ubuntu 16.04 Xenial) i have updated the .travis file also.

**Comment by kadamiec** [comment]
@miracle2k would you be interested in merging?

**Comment by kalimaul** [comment]
I would just like to add that I'd be very interested in having this feature in mainline.

**Comment by kalimaul** [comment]
Is there anything blocking merging this?

**Comment by miracle2k** [comment]
Sorry about the delay on this, it just come in at time when I wasn't able to work on this.

**Pull request merged**
